//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcGisProAppYolo.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcGisProAppYolo.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatically stretches the histogram by clipping extreme values..
        /// </summary>
        public static string Aug_AutoContrast_Desc {
            get {
                return ResourceManager.GetString("Aug_AutoContrast_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Works well for heterogeneous images with unstable exposure..
        /// </summary>
        public static string Aug_AutoContrast_Rec {
            get {
                return ResourceManager.GetString("Aug_AutoContrast_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adjusts image brightness..
        /// </summary>
        public static string Aug_Brightness_Desc {
            get {
                return ResourceManager.GetString("Aug_Brightness_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Small fluctuations help the model generalize between bright and dark scenes..
        /// </summary>
        public static string Aug_Brightness_Rec {
            get {
                return ResourceManager.GetString("Aug_Brightness_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Locally equalizes contrast, enhancing details in dark and bright areas..
        /// </summary>
        public static string Aug_CLAHE_Desc {
            get {
                return ResourceManager.GetString("Aug_CLAHE_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use moderately to avoid amplifying noise..
        /// </summary>
        public static string Aug_CLAHE_Rec {
            get {
                return ResourceManager.GetString("Aug_CLAHE_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increases or decreases contrast between object and background..
        /// </summary>
        public static string Aug_Contrast_Desc {
            get {
                return ResourceManager.GetString("Aug_Contrast_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moderate contrast is useful for robustness to different sensors/exposures..
        /// </summary>
        public static string Aug_Contrast_Rec {
            get {
                return ResourceManager.GetString("Aug_Contrast_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copies objects between images to increase class variability..
        /// </summary>
        public static string Aug_CopyPaste_Desc {
            get {
                return ResourceManager.GetString("Aug_CopyPaste_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Useful for class imbalance and rare objects..
        /// </summary>
        public static string Aug_CopyPaste_Rec {
            get {
                return ResourceManager.GetString("Aug_CopyPaste_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Randomly hides image fragments with rectangular cutouts..
        /// </summary>
        public static string Aug_CutOut_Desc {
            get {
                return ResourceManager.GetString("Aug_CutOut_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Helps with occlusion robustness, but large areas may remove important features..
        /// </summary>
        public static string Aug_CutOut_Rec {
            get {
                return ResourceManager.GetString("Aug_CutOut_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transform modifies the appearance of training images..
        /// </summary>
        public static string Aug_Default_Desc {
            get {
                return ResourceManager.GetString("Aug_Default_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adjust parameters gradually and check the effect in Preview..
        /// </summary>
        public static string Aug_Default_Rec {
            get {
                return ResourceManager.GetString("Aug_Default_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Globally equalizes the brightness histogram..
        /// </summary>
        public static string Aug_Equalize_Desc {
            get {
                return ResourceManager.GetString("Aug_Equalize_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Useful for equalizing contrast across different scenes..
        /// </summary>
        public static string Aug_Equalize_Rec {
            get {
                return ResourceManager.GetString("Aug_Equalize_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Probabilistically erases random image regions..
        /// </summary>
        public static string Aug_Erasing_Desc {
            get {
                return ResourceManager.GetString("Aug_Erasing_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use low/medium probability for moderate regularization..
        /// </summary>
        public static string Aug_Erasing_Rec {
            get {
                return ResourceManager.GetString("Aug_Erasing_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creates a horizontally mirrored copy..
        /// </summary>
        public static string Aug_FlipH_Desc {
            get {
                return ResourceManager.GetString("Aug_FlipH_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Improves robustness to left/right object variations..
        /// </summary>
        public static string Aug_FlipH_Rec {
            get {
                return ResourceManager.GetString("Aug_FlipH_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creates a vertically mirrored copy..
        /// </summary>
        public static string Aug_FlipV_Desc {
            get {
                return ResourceManager.GetString("Aug_FlipV_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use with caution: often useful for aerial data, but may introduce unrealistic scenes..
        /// </summary>
        public static string Aug_FlipV_Rec {
            get {
                return ResourceManager.GetString("Aug_FlipV_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blurs the image with a Gaussian filter..
        /// </summary>
        public static string Aug_GaussianBlur_Desc {
            get {
                return ResourceManager.GetString("Aug_GaussianBlur_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simulates defocus/motion blur; apply large kernels carefully..
        /// </summary>
        public static string Aug_GaussianBlur_Rec {
            get {
                return ResourceManager.GetString("Aug_GaussianBlur_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adds Gaussian noise to pixels..
        /// </summary>
        public static string Aug_GaussianNoise_Desc {
            get {
                return ResourceManager.GetString("Aug_GaussianNoise_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Improves robustness to noisy sensors, but excess degrades label quality..
        /// </summary>
        public static string Aug_GaussianNoise_Rec {
            get {
                return ResourceManager.GetString("Aug_GaussianNoise_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Converts the image to grayscale with a given probability..
        /// </summary>
        public static string Aug_Grayscale_Desc {
            get {
                return ResourceManager.GetString("Aug_Grayscale_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Helps reduce the model&apos;s dependence on color when shape/texture matters more..
        /// </summary>
        public static string Aug_Grayscale_Rec {
            get {
                return ResourceManager.GetString("Aug_Grayscale_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shifts the hue in HSV, changing the color tone of objects and background..
        /// </summary>
        public static string Aug_Hue_Desc {
            get {
                return ResourceManager.GetString("Aug_Hue_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Useful under varying lighting conditions and seasons..
        /// </summary>
        public static string Aug_Hue_Rec {
            get {
                return ResourceManager.GetString("Aug_Hue_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Median blur suppresses impulse noise while preserving edges..
        /// </summary>
        public static string Aug_MedianBlur_Desc {
            get {
                return ResourceManager.GetString("Aug_MedianBlur_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Works well on noisy images without significant loss of contours..
        /// </summary>
        public static string Aug_MedianBlur_Rec {
            get {
                return ResourceManager.GetString("Aug_MedianBlur_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Linearly blends two images and their annotations..
        /// </summary>
        public static string Aug_MixUp_Desc {
            get {
                return ResourceManager.GetString("Aug_MixUp_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Low alpha values usually give the best balance between regularization and readability..
        /// </summary>
        public static string Aug_MixUp_Rec {
            get {
                return ResourceManager.GetString("Aug_MixUp_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Combines 4 images into one to increase object density..
        /// </summary>
        public static string Aug_Mosaic_Desc {
            get {
                return ResourceManager.GetString("Aug_Mosaic_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Strong augmentation for train; enable carefully for stable validation..
        /// </summary>
        public static string Aug_Mosaic_Rec {
            get {
                return ResourceManager.GetString("Aug_Mosaic_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adds perspective distortion to simulate a change in viewpoint..
        /// </summary>
        public static string Aug_Perspective_Desc {
            get {
                return ResourceManager.GetString("Aug_Perspective_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start with small values (0.0005–0.001) to avoid strong deformation..
        /// </summary>
        public static string Aug_Perspective_Rec {
            get {
                return ResourceManager.GetString("Aug_Perspective_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reduces the number of bits per channel, simplifying color gradations..
        /// </summary>
        public static string Aug_Posterize_Desc {
            get {
                return ResourceManager.GetString("Aug_Posterize_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Suitable for improving robustness to quantization/compression..
        /// </summary>
        public static string Aug_Posterize_Rec {
            get {
                return ResourceManager.GetString("Aug_Posterize_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simulates atmospheric rain/fog effects..
        /// </summary>
        public static string Aug_RainFog_Desc {
            get {
                return ResourceManager.GetString("Aug_RainFog_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moderate intensity improves model transferability to bad weather..
        /// </summary>
        public static string Aug_RainFog_Rec {
            get {
                return ResourceManager.GetString("Aug_RainFog_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Randomly crops the image, keeping the selected fraction of the original frame..
        /// </summary>
        public static string Aug_RandomCrop_Desc {
            get {
                return ResourceManager.GetString("Aug_RandomCrop_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lowering the parameter increases diversity but may increase the number of empty tiles..
        /// </summary>
        public static string Aug_RandomCrop_Rec {
            get {
                return ResourceManager.GetString("Aug_RandomCrop_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overlays artificial shadows..
        /// </summary>
        public static string Aug_RandomShadow_Desc {
            get {
                return ResourceManager.GetString("Aug_RandomShadow_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Useful for aerial photos with variable lighting; don&apos;t overuse the application rate..
        /// </summary>
        public static string Aug_RandomShadow_Rec {
            get {
                return ResourceManager.GetString("Aug_RandomShadow_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creates a deterministic copy flipped 180°..
        /// </summary>
        public static string Aug_Rotate180_Desc {
            get {
                return ResourceManager.GetString("Aug_Rotate180_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Improves model robustness to inverted scene orientation..
        /// </summary>
        public static string Aug_Rotate180_Rec {
            get {
                return ResourceManager.GetString("Aug_Rotate180_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creates a deterministic copy by rotating the tile 270° clockwise..
        /// </summary>
        public static string Aug_Rotate270CW_Desc {
            get {
                return ResourceManager.GetString("Aug_Rotate270CW_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add together with other rotations for full orientation coverage..
        /// </summary>
        public static string Aug_Rotate270CW_Rec {
            get {
                return ResourceManager.GetString("Aug_Rotate270CW_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creates a deterministic copy by rotating the tile 90° clockwise..
        /// </summary>
        public static string Aug_Rotate90CW_Desc {
            get {
                return ResourceManager.GetString("Aug_Rotate90CW_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Useful when objects can appear in any orientation relative to the map axis..
        /// </summary>
        public static string Aug_Rotate90CW_Rec {
            get {
                return ResourceManager.GetString("Aug_Rotate90CW_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adds impulse noise (white/black dots)..
        /// </summary>
        public static string Aug_SaltPepper_Desc {
            get {
                return ResourceManager.GetString("Aug_SaltPepper_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use low density to simulate transmission/compression artifacts..
        /// </summary>
        public static string Aug_SaltPepper_Rec {
            get {
                return ResourceManager.GetString("Aug_SaltPepper_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changes color saturation..
        /// </summary>
        public static string Aug_Saturation_Desc {
            get {
                return ResourceManager.GetString("Aug_Saturation_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avoid extremes to prevent unnatural textures..
        /// </summary>
        public static string Aug_Saturation_Rec {
            get {
                return ResourceManager.GetString("Aug_Saturation_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scales the scene, changing the relative size of objects..
        /// </summary>
        public static string Aug_Scale_Desc {
            get {
                return ResourceManager.GetString("Aug_Scale_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A range of about 0.8–1.2 usually gives a realistic effect without significant degradation..
        /// </summary>
        public static string Aug_Scale_Rec {
            get {
                return ResourceManager.GetString("Aug_Scale_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shears the image along the X axis, simulating a perspective shift..
        /// </summary>
        public static string Aug_ShearX_Desc {
            get {
                return ResourceManager.GetString("Aug_ShearX_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moderate values (up to 5–10°) are usually sufficient; larger values may distort objects..
        /// </summary>
        public static string Aug_ShearX_Rec {
            get {
                return ResourceManager.GetString("Aug_ShearX_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shears the image along the Y axis..
        /// </summary>
        public static string Aug_ShearY_Desc {
            get {
                return ResourceManager.GetString("Aug_ShearY_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use together with Shear X for robustness to oblique viewpoints..
        /// </summary>
        public static string Aug_ShearY_Rec {
            get {
                return ResourceManager.GetString("Aug_ShearY_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inverts pixels above a threshold, creating a high-contrast effect..
        /// </summary>
        public static string Aug_Solarize_Desc {
            get {
                return ResourceManager.GetString("Aug_Solarize_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use rarely and with low probability as regularization..
        /// </summary>
        public static string Aug_Solarize_Rec {
            get {
                return ResourceManager.GetString("Aug_Solarize_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shifts the image horizontally..
        /// </summary>
        public static string Aug_TranslateX_Desc {
            get {
                return ResourceManager.GetString("Aug_TranslateX_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Useful for training on offset objects; too large a shift increases the proportion of clipped annotations..
        /// </summary>
        public static string Aug_TranslateX_Rec {
            get {
                return ResourceManager.GetString("Aug_TranslateX_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shifts the image vertically..
        /// </summary>
        public static string Aug_TranslateY_Desc {
            get {
                return ResourceManager.GetString("Aug_TranslateY_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keep the value moderate to avoid losing annotations at the frame edge..
        /// </summary>
        public static string Aug_TranslateY_Rec {
            get {
                return ResourceManager.GetString("Aug_TranslateY_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse....
        /// </summary>
        public static string Common_Browse {
            get {
                return ResourceManager.GetString("Common_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancelling....
        /// </summary>
        public static string Common_Cancelling {
            get {
                return ResourceManager.GetString("Common_Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation cancelled..
        /// </summary>
        public static string Common_OperationCancelled {
            get {
                return ResourceManager.GetString("Common_OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation cancelled by user..
        /// </summary>
        public static string Common_OperationCancelledByUser {
            get {
                return ResourceManager.GetString("Common_OperationCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preparing....
        /// </summary>
        public static string Common_Preparing {
            get {
                return ResourceManager.GetString("Common_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Progress.
        /// </summary>
        public static string Common_Progress {
            get {
                return ResourceManager.GetString("Common_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh list..
        /// </summary>
        public static string Common_RefreshTooltip {
            get {
                return ResourceManager.GetString("Common_RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset.
        /// </summary>
        public static string Common_Reset {
            get {
                return ResourceManager.GetString("Common_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run.
        /// </summary>
        public static string Common_Run {
            get {
                return ResourceManager.GetString("Common_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Dataset.
        /// </summary>
        public static string Daml_CreateDatasetCaption {
            get {
                return ResourceManager.GetString("Daml_CreateDatasetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Detection.
        /// </summary>
        public static string Daml_DetectionCaption {
            get {
                return ResourceManager.GetString("Daml_DetectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на YOLO Tool.
        /// </summary>
        public static string Daml_GroupCaption {
            get {
                return ResourceManager.GetString("Daml_GroupCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yolo Detection.
        /// </summary>
        public static string Daml_YoloDetectionCaption {
            get {
                return ResourceManager.GetString("Daml_YoloDetectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Annotation Layers.
        /// </summary>
        public static string Dataset_AnnotationLayers {
            get {
                return ResourceManager.GetString("Dataset_AnnotationLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only layers with &apos;train&apos; in the name are shown..
        /// </summary>
        public static string Dataset_AnnotationLayersFilter {
            get {
                return ResourceManager.GetString("Dataset_AnnotationLayersFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Layer filter: name contains train..
        /// </summary>
        public static string Dataset_AnnotationLayersFilterTooltip {
            get {
                return ResourceManager.GetString("Dataset_AnnotationLayersFilterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Applied:.
        /// </summary>
        public static string Dataset_Applied {
            get {
                return ResourceManager.GetString("Dataset_Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Applying transform....
        /// </summary>
        public static string Dataset_ApplyingTransform {
            get {
                return ResourceManager.GetString("Dataset_ApplyingTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply Next Transform.
        /// </summary>
        public static string Dataset_ApplyNextTransform {
            get {
                return ResourceManager.GetString("Dataset_ApplyNextTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply the next transform (round-robin) to the current image..
        /// </summary>
        public static string Dataset_ApplyNextTransformTooltip {
            get {
                return ResourceManager.GetString("Dataset_ApplyNextTransformTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply selected:.
        /// </summary>
        public static string Dataset_ApplySelected {
            get {
                return ResourceManager.GetString("Dataset_ApplySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select an enabled transform to apply it to the current tile immediately..
        /// </summary>
        public static string Dataset_ApplySelectedTooltip {
            get {
                return ResourceManager.GetString("Dataset_ApplySelectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply to Test.
        /// </summary>
        public static string Dataset_ApplyToTest {
            get {
                return ResourceManager.GetString("Dataset_ApplyToTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If enabled: augmentation is also applied to the test split. Recommended to disable for objective final model testing..
        /// </summary>
        public static string Dataset_ApplyToTestTooltip {
            get {
                return ResourceManager.GetString("Dataset_ApplyToTestTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply to Val.
        /// </summary>
        public static string Dataset_ApplyToVal {
            get {
                return ResourceManager.GetString("Dataset_ApplyToVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If enabled: augmentation is also applied to the validation split. Usually left off so metrics reflect quality on &apos;clean&apos; data..
        /// </summary>
        public static string Dataset_ApplyToValTooltip {
            get {
                return ResourceManager.GetString("Dataset_ApplyToValTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable/disable augmentation..
        /// </summary>
        public static string Dataset_AugmentationEnableTooltip {
            get {
                return ResourceManager.GetString("Dataset_AugmentationEnableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Available: {0}.
        /// </summary>
        public static string Dataset_AvailableFormat {
            get {
                return ResourceManager.GetString("Dataset_AvailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Background / Class Balance / Debug.
        /// </summary>
        public static string Dataset_BackgroundHeader {
            get {
                return ResourceManager.GetString("Dataset_BackgroundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Background limit:.
        /// </summary>
        public static string Dataset_BackgroundLimit {
            get {
                return ResourceManager.GetString("Dataset_BackgroundLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balancing method:.
        /// </summary>
        public static string Dataset_BalancingMethod {
            get {
                return ResourceManager.GetString("Dataset_BalancingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a tiles folder for preview..
        /// </summary>
        public static string Dataset_BrowsePreviewTooltip {
            get {
                return ResourceManager.GetString("Dataset_BrowsePreviewTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Built-in presets:.
        /// </summary>
        public static string Dataset_BuiltInPresets {
            get {
                return ResourceManager.GetString("Dataset_BuiltInPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Dataset.
        /// </summary>
        public static string Dataset_CreateDataset {
            get {
                return ResourceManager.GetString("Dataset_CreateDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current tile:.
        /// </summary>
        public static string Dataset_CurrentTile {
            get {
                return ResourceManager.GetString("Dataset_CurrentTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current tile file for preview..
        /// </summary>
        public static string Dataset_CurrentTileTooltip {
            get {
                return ResourceManager.GetString("Dataset_CurrentTileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data Augmentation.
        /// </summary>
        public static string Dataset_DataAugmentation {
            get {
                return ResourceManager.GetString("Dataset_DataAugmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dataset multiplier: ×{0}.
        /// </summary>
        public static string Dataset_DatasetMultiplierFormat {
            get {
                return ResourceManager.GetString("Dataset_DatasetMultiplierFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dataset Type.
        /// </summary>
        public static string Dataset_DatasetType {
            get {
                return ResourceManager.GetString("Dataset_DatasetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Annotation format in Ultralytics YOLO style..
        /// </summary>
        public static string Dataset_DatasetTypeTooltip {
            get {
                return ResourceManager.GetString("Dataset_DatasetTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Debug Mode.
        /// </summary>
        public static string Dataset_DebugMode {
            get {
                return ResourceManager.GetString("Dataset_DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save visualizations and additional debug artifacts..
        /// </summary>
        public static string Dataset_DebugModeTooltip {
            get {
                return ResourceManager.GetString("Dataset_DebugModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease lower threshold..
        /// </summary>
        public static string Dataset_DecrementLowerTooltip {
            get {
                return ResourceManager.GetString("Dataset_DecrementLowerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease probability..
        /// </summary>
        public static string Dataset_DecrementProbTooltip {
            get {
                return ResourceManager.GetString("Dataset_DecrementProbTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease upper threshold..
        /// </summary>
        public static string Dataset_DecrementUpperTooltip {
            get {
                return ResourceManager.GetString("Dataset_DecrementUpperTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable class balancing.
        /// </summary>
        public static string Dataset_EnableClassBalancing {
            get {
                return ResourceManager.GetString("Dataset_EnableClassBalancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class balancing for Train/Val..
        /// </summary>
        public static string Dataset_EnableClassBalancingTooltip {
            get {
                return ResourceManager.GetString("Dataset_EnableClassBalancingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Estimated source images:.
        /// </summary>
        public static string Dataset_EstimatedSourceImages {
            get {
                return ResourceManager.GetString("Dataset_EstimatedSourceImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Estimated generation time: {0}.
        /// </summary>
        public static string Dataset_EstimatedTimeFormat {
            get {
                return ResourceManager.GetString("Dataset_EstimatedTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Estimated total images: {0}.
        /// </summary>
        public static string Dataset_EstimatedTotalFormat {
            get {
                return ResourceManager.GetString("Dataset_EstimatedTotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export hyp.yaml.
        /// </summary>
        public static string Dataset_ExportHyp {
            get {
                return ResourceManager.GetString("Dataset_ExportHyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export parameters in hyp.yaml format for Ultralytics YOLO (convenient for CLI training)..
        /// </summary>
        public static string Dataset_ExportHypTooltip {
            get {
                return ResourceManager.GetString("Dataset_ExportHypTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase lower threshold..
        /// </summary>
        public static string Dataset_IncrementLowerTooltip {
            get {
                return ResourceManager.GetString("Dataset_IncrementLowerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase probability..
        /// </summary>
        public static string Dataset_IncrementProbTooltip {
            get {
                return ResourceManager.GetString("Dataset_IncrementProbTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase upper threshold..
        /// </summary>
        public static string Dataset_IncrementUpperTooltip {
            get {
                return ResourceManager.GetString("Dataset_IncrementUpperTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load preset (.json).
        /// </summary>
        public static string Dataset_LoadPreset {
            get {
                return ResourceManager.GetString("Dataset_LoadPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load a previously saved JSON preset and apply it to the current panel..
        /// </summary>
        public static string Dataset_LoadPresetTooltip {
            get {
                return ResourceManager.GetString("Dataset_LoadPresetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum allowed probability..
        /// </summary>
        public static string Dataset_MaxProbTooltip {
            get {
                return ResourceManager.GetString("Dataset_MaxProbTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum allowed probability..
        /// </summary>
        public static string Dataset_MinProbTooltip {
            get {
                return ResourceManager.GetString("Dataset_MinProbTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next image.
        /// </summary>
        public static string Dataset_NextImageTooltip {
            get {
                return ResourceManager.GetString("Dataset_NextImageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Source ortho image not found in Products/Orthos..
        /// </summary>
        public static string Dataset_OrthoNotFound {
            get {
                return ResourceManager.GetString("Dataset_OrthoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ortho Selection.
        /// </summary>
        public static string Dataset_OrthoSelection {
            get {
                return ResourceManager.GetString("Dataset_OrthoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select an orthophoto from the current ArcGIS Pro project..
        /// </summary>
        public static string Dataset_OrthoTooltip {
            get {
                return ResourceManager.GetString("Dataset_OrthoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overlap (0..0.9):.
        /// </summary>
        public static string Dataset_Overlap {
            get {
                return ResourceManager.GetString("Dataset_Overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For example 0.2 = 20%..
        /// </summary>
        public static string Dataset_OverlapTooltip {
            get {
                return ResourceManager.GetString("Dataset_OverlapTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Percent.
        /// </summary>
        public static string Dataset_Percent {
            get {
                return ResourceManager.GetString("Dataset_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum augmentations. Use carefully and check for quality degradation..
        /// </summary>
        public static string Dataset_PresetAggressiveTooltip {
            get {
                return ResourceManager.GetString("Dataset_PresetAggressiveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light and safe augmentations: minimal geometric/color changes..
        /// </summary>
        public static string Dataset_PresetLightTooltip {
            get {
                return ResourceManager.GetString("Dataset_PresetLightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable all augmentations and restore defaults..
        /// </summary>
        public static string Dataset_PresetNoneTooltip {
            get {
                return ResourceManager.GetString("Dataset_PresetNoneTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set for outdoor/aerial scenes: shadows, fog, local contrast..
        /// </summary>
        public static string Dataset_PresetOutdoorAerialTooltip {
            get {
                return ResourceManager.GetString("Dataset_PresetOutdoorAerialTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preset — a ready-made set of enabled augmentations, their ranges and probabilities. Use as a starting point, then adjust for your dataset..
        /// </summary>
        public static string Dataset_PresetsDescription {
            get {
                return ResourceManager.GetString("Dataset_PresetsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balanced set for most detection/segmentation tasks..
        /// </summary>
        public static string Dataset_PresetStandardTooltip {
            get {
                return ResourceManager.GetString("Dataset_PresetStandardTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a tiles folder: the first image will load. Use ←/→ buttons to switch images. Press Apply Next Transform to apply the next enabled transform..
        /// </summary>
        public static string Dataset_PreviewInstructions {
            get {
                return ResourceManager.GetString("Dataset_PreviewInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous image.
        /// </summary>
        public static string Dataset_PrevImageTooltip {
            get {
                return ResourceManager.GetString("Dataset_PrevImageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Probability:.
        /// </summary>
        public static string Dataset_Probability {
            get {
                return ResourceManager.GetString("Dataset_Probability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application probability (0..1)..
        /// </summary>
        public static string Dataset_ProbabilityTooltip {
            get {
                return ResourceManager.GetString("Dataset_ProbabilityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Range:.
        /// </summary>
        public static string Dataset_Range {
            get {
                return ResourceManager.GetString("Dataset_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lower bound of range..
        /// </summary>
        public static string Dataset_RangeLowerTooltip {
            get {
                return ResourceManager.GetString("Dataset_RangeLowerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upper bound of range..
        /// </summary>
        public static string Dataset_RangeUpperTooltip {
            get {
                return ResourceManager.GetString("Dataset_RangeUpperTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recommendation: {0}.
        /// </summary>
        public static string Dataset_RecommendationFormat {
            get {
                return ResourceManager.GetString("Dataset_RecommendationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh list (only layers with train in name)..
        /// </summary>
        public static string Dataset_RefreshAnnotationTooltip {
            get {
                return ResourceManager.GetString("Dataset_RefreshAnnotationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh orthophoto list..
        /// </summary>
        public static string Dataset_RefreshOrthoTooltip {
            get {
                return ResourceManager.GetString("Dataset_RefreshOrthoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset to default values..
        /// </summary>
        public static string Dataset_ResetTooltip {
            get {
                return ResourceManager.GetString("Dataset_ResetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Running....
        /// </summary>
        public static string Dataset_Running {
            get {
                return ResourceManager.GetString("Dataset_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start dataset creation..
        /// </summary>
        public static string Dataset_RunTooltip {
            get {
                return ResourceManager.GetString("Dataset_RunTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save preset (.json).
        /// </summary>
        public static string Dataset_SavePreset {
            get {
                return ResourceManager.GetString("Dataset_SavePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save current augmentation settings (including ranges and probabilities) to a JSON file for reuse..
        /// </summary>
        public static string Dataset_SavePresetTooltip {
            get {
                return ResourceManager.GetString("Dataset_SavePresetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Seed:.
        /// </summary>
        public static string Dataset_Seed {
            get {
                return ResourceManager.GetString("Dataset_Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fixed seed for reproducibility..
        /// </summary>
        public static string Dataset_SeedTooltip {
            get {
                return ResourceManager.GetString("Dataset_SeedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Annotation layers selected:.
        /// </summary>
        public static string Dataset_SelectedAnnotationLayersSummary {
            get {
                return ResourceManager.GetString("Dataset_SelectedAnnotationLayersSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slicing Parameters.
        /// </summary>
        public static string Dataset_SlicingParameters {
            get {
                return ResourceManager.GetString("Dataset_SlicingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Train / Val / Test Split.
        /// </summary>
        public static string Dataset_SplitHeader {
            get {
                return ResourceManager.GetString("Dataset_SplitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Summary.
        /// </summary>
        public static string Dataset_Summary {
            get {
                return ResourceManager.GetString("Dataset_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚡ Advanced.
        /// </summary>
        public static string Dataset_TabAdvanced {
            get {
                return ResourceManager.GetString("Dataset_TabAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🎨 Color.
        /// </summary>
        public static string Dataset_TabColor {
            get {
                return ResourceManager.GetString("Dataset_TabColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📐 Geometry.
        /// </summary>
        public static string Dataset_TabGeometry {
            get {
                return ResourceManager.GetString("Dataset_TabGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🌫️ Noise &amp; Blur.
        /// </summary>
        public static string Dataset_TabNoiseBlur {
            get {
                return ResourceManager.GetString("Dataset_TabNoiseBlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 💾 Presets.
        /// </summary>
        public static string Dataset_TabPresets {
            get {
                return ResourceManager.GetString("Dataset_TabPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 👁️ Preview.
        /// </summary>
        public static string Dataset_TabPreview {
            get {
                return ResourceManager.GetString("Dataset_TabPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tiles for size {0}px already exist. Use existing?
        ///
        ///Yes — use existing
        ///No — regenerate
        ///Cancel — abort operation.
        /// </summary>
        public static string Dataset_TilesExistMessage {
            get {
                return ResourceManager.GetString("Dataset_TilesExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tiles already exist.
        /// </summary>
        public static string Dataset_TilesExistTitle {
            get {
                return ResourceManager.GetString("Dataset_TilesExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tiles folder:.
        /// </summary>
        public static string Dataset_TilesFolder {
            get {
                return ResourceManager.GetString("Dataset_TilesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path to the tiles folder for preview..
        /// </summary>
        public static string Dataset_TilesFolderTooltip {
            get {
                return ResourceManager.GetString("Dataset_TilesFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tile Size (px):.
        /// </summary>
        public static string Dataset_TileSizePx {
            get {
                return ResourceManager.GetString("Dataset_TileSizePx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recommended range 64..2048..
        /// </summary>
        public static string Dataset_TileSizeTooltip {
            get {
                return ResourceManager.GetString("Dataset_TileSizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Available: {0} item(s).
        /// </summary>
        public static string Yolo_AvailableFormat {
            get {
                return ResourceManager.GetString("Yolo_AvailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a model file (.pt/.onnx)..
        /// </summary>
        public static string Yolo_BrowseModelTooltip {
            get {
                return ResourceManager.GetString("Yolo_BrowseModelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confidence:.
        /// </summary>
        public static string Yolo_Confidence {
            get {
                return ResourceManager.GetString("Yolo_Confidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model confidence threshold (0..1)..
        /// </summary>
        public static string Yolo_ConfidenceTooltip {
            get {
                return ResourceManager.GetString("Yolo_ConfidenceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Objects below threshold are discarded..
        /// </summary>
        public static string Yolo_ConfidenceValueTooltip {
            get {
                return ResourceManager.GetString("Yolo_ConfidenceValueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Detection Settings.
        /// </summary>
        public static string Yolo_DetectionSettings {
            get {
                return ResourceManager.GetString("Yolo_DetectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error: {0}.
        /// </summary>
        public static string Yolo_ErrorGeneric {
            get {
                return ResourceManager.GetString("Yolo_ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to recreate tiles folder: {0}.
        /// </summary>
        public static string Yolo_FailedRecreateTilesFolder {
            get {
                return ResourceManager.GetString("Yolo_FailedRecreateTilesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generating tiles (this may take a while)....
        /// </summary>
        public static string Yolo_GeneratingTiles {
            get {
                return ResourceManager.GetString("Yolo_GeneratingTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mask Mode.
        /// </summary>
        public static string Yolo_MaskMode {
            get {
                return ResourceManager.GetString("Yolo_MaskMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Largest.
        /// </summary>
        public static string Yolo_MaskModeLargest {
            get {
                return ResourceManager.GetString("Yolo_MaskModeLargest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keep only the largest contour (1 mask = 1 object)..
        /// </summary>
        public static string Yolo_MaskModeLargestTooltip {
            get {
                return ResourceManager.GetString("Yolo_MaskModeLargestTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How to form a mask when multiple contours exist..
        /// </summary>
        public static string Yolo_MaskModeTooltip {
            get {
                return ResourceManager.GetString("Yolo_MaskModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Union.
        /// </summary>
        public static string Yolo_MaskModeUnion {
            get {
                return ResourceManager.GetString("Yolo_MaskModeUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merge all contours into one geometry..
        /// </summary>
        public static string Yolo_MaskModeUnionTooltip {
            get {
                return ResourceManager.GetString("Yolo_MaskModeUnionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model Configuration.
        /// </summary>
        public static string Yolo_ModelConfiguration {
            get {
                return ResourceManager.GetString("Yolo_ModelConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model file not specified or not found..
        /// </summary>
        public static string Yolo_ModelNotFound {
            get {
                return ResourceManager.GetString("Yolo_ModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ortho image not found in selected Ortho..
        /// </summary>
        public static string Yolo_OrthoImageNotFound {
            get {
                return ResourceManager.GetString("Yolo_OrthoImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of available project orthophotos..
        /// </summary>
        public static string Yolo_OrthoListTooltip {
            get {
                return ResourceManager.GetString("Yolo_OrthoListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ortho Selection.
        /// </summary>
        public static string Yolo_OrthoSelection {
            get {
                return ResourceManager.GetString("Yolo_OrthoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Output Boxes.
        /// </summary>
        public static string Yolo_OutputBoxes {
            get {
                return ResourceManager.GetString("Yolo_OutputBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a bounding box layer..
        /// </summary>
        public static string Yolo_OutputBoxesTooltip {
            get {
                return ResourceManager.GetString("Yolo_OutputBoxesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Output Masks.
        /// </summary>
        public static string Yolo_OutputMasks {
            get {
                return ResourceManager.GetString("Yolo_OutputMasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a polygon mask layer..
        /// </summary>
        public static string Yolo_OutputMasksTooltip {
            get {
                return ResourceManager.GetString("Yolo_OutputMasksTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Output OBB.
        /// </summary>
        public static string Yolo_OutputOBB {
            get {
                return ResourceManager.GetString("Yolo_OutputOBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create an oriented bounding box layer..
        /// </summary>
        public static string Yolo_OutputOBBTooltip {
            get {
                return ResourceManager.GetString("Yolo_OutputOBBTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Output Points.
        /// </summary>
        public static string Yolo_OutputPoints {
            get {
                return ResourceManager.GetString("Yolo_OutputPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a point layer for object centers..
        /// </summary>
        public static string Yolo_OutputPointsTooltip {
            get {
                return ResourceManager.GetString("Yolo_OutputPointsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overlap (%):.
        /// </summary>
        public static string Yolo_OverlapPercent {
            get {
                return ResourceManager.GetString("Yolo_OverlapPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overlap between adjacent tiles in percent..
        /// </summary>
        public static string Yolo_OverlapTooltip {
            get {
                return ResourceManager.GetString("Yolo_OverlapTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More overlap reduces misses at tile borders..
        /// </summary>
        public static string Yolo_OverlapValueTooltip {
            get {
                return ResourceManager.GetString("Yolo_OverlapValueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Predictions completed..
        /// </summary>
        public static string Yolo_PredictionsCompleted {
            get {
                return ResourceManager.GetString("Yolo_PredictionsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Predictions failed (exit {0}). See logs..
        /// </summary>
        public static string Yolo_PredictionsFailed {
            get {
                return ResourceManager.GetString("Yolo_PredictionsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на predict_module.py not found; skipping predictions..
        /// </summary>
        public static string Yolo_PredictModuleNotFound {
            get {
                return ResourceManager.GetString("Yolo_PredictModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preparing Tiles folder....
        /// </summary>
        public static string Yolo_PreparingTilesFolder {
            get {
                return ResourceManager.GetString("Yolo_PreparingTilesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full line-by-line execution log. You can select and copy..
        /// </summary>
        public static string Yolo_ProgressTooltip {
            get {
                return ResourceManager.GetString("Yolo_ProgressTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project or Ortho not selected..
        /// </summary>
        public static string Yolo_ProjectOrOrthoNotSelected {
            get {
                return ResourceManager.GetString("Yolo_ProjectOrOrthoNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh orthophoto list..
        /// </summary>
        public static string Yolo_RefreshOrthoTooltip {
            get {
                return ResourceManager.GetString("Yolo_RefreshOrthoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start detection. During execution the button switches to Cancel..
        /// </summary>
        public static string Yolo_RunButtonTooltip {
            get {
                return ResourceManager.GetString("Yolo_RunButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run Detection.
        /// </summary>
        public static string Yolo_RunDetection {
            get {
                return ResourceManager.GetString("Yolo_RunDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Running predictions....
        /// </summary>
        public static string Yolo_RunningPredictions {
            get {
                return ResourceManager.GetString("Yolo_RunningPredictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Ortho:.
        /// </summary>
        public static string Yolo_SelectOrtho {
            get {
                return ResourceManager.GetString("Yolo_SelectOrtho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select an orthophoto for processing..
        /// </summary>
        public static string Yolo_SelectOrthoTooltip {
            get {
                return ResourceManager.GetString("Yolo_SelectOrthoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tiles generation completed..
        /// </summary>
        public static string Yolo_TilesCompleted {
            get {
                return ResourceManager.GetString("Yolo_TilesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tile Settings.
        /// </summary>
        public static string Yolo_TileSettings {
            get {
                return ResourceManager.GetString("Yolo_TileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tiles for size {0}px already exist. Use existing?
        ///
        ///Yes — use existing
        ///No — regenerate
        ///Cancel — abort operation.
        /// </summary>
        public static string Yolo_TilesExistMessage {
            get {
                return ResourceManager.GetString("Yolo_TilesExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tiles already exist.
        /// </summary>
        public static string Yolo_TilesExistTitle {
            get {
                return ResourceManager.GetString("Yolo_TilesExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tiles generation failed. See logs in Tiles folder..
        /// </summary>
        public static string Yolo_TilesGenerationFailed {
            get {
                return ResourceManager.GetString("Yolo_TilesGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tile Size:.
        /// </summary>
        public static string Yolo_TileSize {
            get {
                return ResourceManager.GetString("Yolo_TileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tile size in pixels..
        /// </summary>
        public static string Yolo_TileSizeTooltip {
            get {
                return ResourceManager.GetString("Yolo_TileSizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Larger tiles consume more memory..
        /// </summary>
        public static string Yolo_TileSizeValueTooltip {
            get {
                return ResourceManager.GetString("Yolo_TileSizeValueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use SAHI slicing.
        /// </summary>
        public static string Yolo_UseSahi {
            get {
                return ResourceManager.GetString("Yolo_UseSahi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kept for compatibility; uses SAHI..
        /// </summary>
        public static string Yolo_UseSahiTooltip {
            get {
                return ResourceManager.GetString("Yolo_UseSahiTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Using existing tiles..
        /// </summary>
        public static string Yolo_UsingExistingTiles {
            get {
                return ResourceManager.GetString("Yolo_UsingExistingTiles", resourceCulture);
            }
        }
    }
}
