//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcGisProAppYolo.Resources {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcGisProAppYolo.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Common_Run { get { return ResourceManager.GetString("Common_Run", resourceCulture); } }
        public static string Common_Cancel { get { return ResourceManager.GetString("Common_Cancel", resourceCulture); } }
        public static string Common_Browse { get { return ResourceManager.GetString("Common_Browse", resourceCulture); } }
        public static string Common_Reset { get { return ResourceManager.GetString("Common_Reset", resourceCulture); } }
        public static string Common_Progress { get { return ResourceManager.GetString("Common_Progress", resourceCulture); } }
        public static string Common_RefreshTooltip { get { return ResourceManager.GetString("Common_RefreshTooltip", resourceCulture); } }
        public static string Common_OperationCancelledByUser { get { return ResourceManager.GetString("Common_OperationCancelledByUser", resourceCulture); } }
        public static string Common_OperationCancelled { get { return ResourceManager.GetString("Common_OperationCancelled", resourceCulture); } }
        public static string Common_Preparing { get { return ResourceManager.GetString("Common_Preparing", resourceCulture); } }
        public static string Common_Cancelling { get { return ResourceManager.GetString("Common_Cancelling", resourceCulture); } }

        public static string Yolo_OrthoSelection { get { return ResourceManager.GetString("Yolo_OrthoSelection", resourceCulture); } }
        public static string Yolo_SelectOrtho { get { return ResourceManager.GetString("Yolo_SelectOrtho", resourceCulture); } }
        public static string Yolo_SelectOrthoTooltip { get { return ResourceManager.GetString("Yolo_SelectOrthoTooltip", resourceCulture); } }
        public static string Yolo_OrthoListTooltip { get { return ResourceManager.GetString("Yolo_OrthoListTooltip", resourceCulture); } }
        public static string Yolo_RefreshOrthoTooltip { get { return ResourceManager.GetString("Yolo_RefreshOrthoTooltip", resourceCulture); } }
        public static string Yolo_AvailableFormat { get { return ResourceManager.GetString("Yolo_AvailableFormat", resourceCulture); } }
        public static string Yolo_ModelConfiguration { get { return ResourceManager.GetString("Yolo_ModelConfiguration", resourceCulture); } }
        public static string Yolo_BrowseModelTooltip { get { return ResourceManager.GetString("Yolo_BrowseModelTooltip", resourceCulture); } }
        public static string Yolo_TileSettings { get { return ResourceManager.GetString("Yolo_TileSettings", resourceCulture); } }
        public static string Yolo_TileSize { get { return ResourceManager.GetString("Yolo_TileSize", resourceCulture); } }
        public static string Yolo_TileSizeTooltip { get { return ResourceManager.GetString("Yolo_TileSizeTooltip", resourceCulture); } }
        public static string Yolo_TileSizeValueTooltip { get { return ResourceManager.GetString("Yolo_TileSizeValueTooltip", resourceCulture); } }
        public static string Yolo_OverlapPercent { get { return ResourceManager.GetString("Yolo_OverlapPercent", resourceCulture); } }
        public static string Yolo_OverlapTooltip { get { return ResourceManager.GetString("Yolo_OverlapTooltip", resourceCulture); } }
        public static string Yolo_OverlapValueTooltip { get { return ResourceManager.GetString("Yolo_OverlapValueTooltip", resourceCulture); } }
        public static string Yolo_DetectionSettings { get { return ResourceManager.GetString("Yolo_DetectionSettings", resourceCulture); } }
        public static string Yolo_Confidence { get { return ResourceManager.GetString("Yolo_Confidence", resourceCulture); } }
        public static string Yolo_ConfidenceTooltip { get { return ResourceManager.GetString("Yolo_ConfidenceTooltip", resourceCulture); } }
        public static string Yolo_ConfidenceValueTooltip { get { return ResourceManager.GetString("Yolo_ConfidenceValueTooltip", resourceCulture); } }
        public static string Yolo_OutputPoints { get { return ResourceManager.GetString("Yolo_OutputPoints", resourceCulture); } }
        public static string Yolo_OutputPointsTooltip { get { return ResourceManager.GetString("Yolo_OutputPointsTooltip", resourceCulture); } }
        public static string Yolo_OutputMasks { get { return ResourceManager.GetString("Yolo_OutputMasks", resourceCulture); } }
        public static string Yolo_OutputMasksTooltip { get { return ResourceManager.GetString("Yolo_OutputMasksTooltip", resourceCulture); } }
        public static string Yolo_OutputBoxes { get { return ResourceManager.GetString("Yolo_OutputBoxes", resourceCulture); } }
        public static string Yolo_OutputBoxesTooltip { get { return ResourceManager.GetString("Yolo_OutputBoxesTooltip", resourceCulture); } }
        public static string Yolo_OutputOBB { get { return ResourceManager.GetString("Yolo_OutputOBB", resourceCulture); } }
        public static string Yolo_OutputOBBTooltip { get { return ResourceManager.GetString("Yolo_OutputOBBTooltip", resourceCulture); } }
        public static string Yolo_UseSahi { get { return ResourceManager.GetString("Yolo_UseSahi", resourceCulture); } }
        public static string Yolo_UseSahiTooltip { get { return ResourceManager.GetString("Yolo_UseSahiTooltip", resourceCulture); } }
        public static string Yolo_MaskMode { get { return ResourceManager.GetString("Yolo_MaskMode", resourceCulture); } }
        public static string Yolo_MaskModeTooltip { get { return ResourceManager.GetString("Yolo_MaskModeTooltip", resourceCulture); } }
        public static string Yolo_MaskModeLargest { get { return ResourceManager.GetString("Yolo_MaskModeLargest", resourceCulture); } }
        public static string Yolo_MaskModeLargestTooltip { get { return ResourceManager.GetString("Yolo_MaskModeLargestTooltip", resourceCulture); } }
        public static string Yolo_MaskModeUnion { get { return ResourceManager.GetString("Yolo_MaskModeUnion", resourceCulture); } }
        public static string Yolo_MaskModeUnionTooltip { get { return ResourceManager.GetString("Yolo_MaskModeUnionTooltip", resourceCulture); } }
        public static string Yolo_RunDetection { get { return ResourceManager.GetString("Yolo_RunDetection", resourceCulture); } }
        public static string Yolo_RunButtonTooltip { get { return ResourceManager.GetString("Yolo_RunButtonTooltip", resourceCulture); } }
        public static string Yolo_ProgressTooltip { get { return ResourceManager.GetString("Yolo_ProgressTooltip", resourceCulture); } }
        public static string Yolo_ProjectOrOrthoNotSelected { get { return ResourceManager.GetString("Yolo_ProjectOrOrthoNotSelected", resourceCulture); } }
        public static string Yolo_OrthoImageNotFound { get { return ResourceManager.GetString("Yolo_OrthoImageNotFound", resourceCulture); } }
        public static string Yolo_PreparingTilesFolder { get { return ResourceManager.GetString("Yolo_PreparingTilesFolder", resourceCulture); } }
        public static string Yolo_TilesExistMessage { get { return ResourceManager.GetString("Yolo_TilesExistMessage", resourceCulture); } }
        public static string Yolo_TilesExistTitle { get { return ResourceManager.GetString("Yolo_TilesExistTitle", resourceCulture); } }
        public static string Yolo_GeneratingTiles { get { return ResourceManager.GetString("Yolo_GeneratingTiles", resourceCulture); } }
        public static string Yolo_UsingExistingTiles { get { return ResourceManager.GetString("Yolo_UsingExistingTiles", resourceCulture); } }
        public static string Yolo_TilesCompleted { get { return ResourceManager.GetString("Yolo_TilesCompleted", resourceCulture); } }
        public static string Yolo_RunningPredictions { get { return ResourceManager.GetString("Yolo_RunningPredictions", resourceCulture); } }
        public static string Yolo_ModelNotFound { get { return ResourceManager.GetString("Yolo_ModelNotFound", resourceCulture); } }
        public static string Yolo_PredictionsCompleted { get { return ResourceManager.GetString("Yolo_PredictionsCompleted", resourceCulture); } }
        public static string Yolo_PredictionsFailed { get { return ResourceManager.GetString("Yolo_PredictionsFailed", resourceCulture); } }
        public static string Yolo_PredictModuleNotFound { get { return ResourceManager.GetString("Yolo_PredictModuleNotFound", resourceCulture); } }
        public static string Yolo_TilesGenerationFailed { get { return ResourceManager.GetString("Yolo_TilesGenerationFailed", resourceCulture); } }
        public static string Yolo_FailedRecreateTilesFolder { get { return ResourceManager.GetString("Yolo_FailedRecreateTilesFolder", resourceCulture); } }
        public static string Yolo_ErrorGeneric { get { return ResourceManager.GetString("Yolo_ErrorGeneric", resourceCulture); } }

        public static string Dataset_OrthoSelection { get { return ResourceManager.GetString("Dataset_OrthoSelection", resourceCulture); } }
        public static string Dataset_OrthoTooltip { get { return ResourceManager.GetString("Dataset_OrthoTooltip", resourceCulture); } }
        public static string Dataset_RefreshOrthoTooltip { get { return ResourceManager.GetString("Dataset_RefreshOrthoTooltip", resourceCulture); } }
        public static string Dataset_AvailableFormat { get { return ResourceManager.GetString("Dataset_AvailableFormat", resourceCulture); } }
        public static string Dataset_AnnotationLayers { get { return ResourceManager.GetString("Dataset_AnnotationLayers", resourceCulture); } }
        public static string Dataset_AnnotationLayersFilter { get { return ResourceManager.GetString("Dataset_AnnotationLayersFilter", resourceCulture); } }
        public static string Dataset_AnnotationLayersFilterTooltip { get { return ResourceManager.GetString("Dataset_AnnotationLayersFilterTooltip", resourceCulture); } }
        public static string Dataset_RefreshAnnotationTooltip { get { return ResourceManager.GetString("Dataset_RefreshAnnotationTooltip", resourceCulture); } }
        public static string Dataset_SlicingParameters { get { return ResourceManager.GetString("Dataset_SlicingParameters", resourceCulture); } }
        public static string Dataset_TileSizePx { get { return ResourceManager.GetString("Dataset_TileSizePx", resourceCulture); } }
        public static string Dataset_TileSizeTooltip { get { return ResourceManager.GetString("Dataset_TileSizeTooltip", resourceCulture); } }
        public static string Dataset_Overlap { get { return ResourceManager.GetString("Dataset_Overlap", resourceCulture); } }
        public static string Dataset_OverlapTooltip { get { return ResourceManager.GetString("Dataset_OverlapTooltip", resourceCulture); } }
        public static string Dataset_DatasetType { get { return ResourceManager.GetString("Dataset_DatasetType", resourceCulture); } }
        public static string Dataset_DatasetTypeTooltip { get { return ResourceManager.GetString("Dataset_DatasetTypeTooltip", resourceCulture); } }
        public static string Dataset_SplitHeader { get { return ResourceManager.GetString("Dataset_SplitHeader", resourceCulture); } }
        public static string Dataset_BackgroundHeader { get { return ResourceManager.GetString("Dataset_BackgroundHeader", resourceCulture); } }
        public static string Dataset_BackgroundLimit { get { return ResourceManager.GetString("Dataset_BackgroundLimit", resourceCulture); } }
        public static string Dataset_Percent { get { return ResourceManager.GetString("Dataset_Percent", resourceCulture); } }
        public static string Dataset_EnableClassBalancing { get { return ResourceManager.GetString("Dataset_EnableClassBalancing", resourceCulture); } }
        public static string Dataset_EnableClassBalancingTooltip { get { return ResourceManager.GetString("Dataset_EnableClassBalancingTooltip", resourceCulture); } }
        public static string Dataset_BalancingMethod { get { return ResourceManager.GetString("Dataset_BalancingMethod", resourceCulture); } }
        public static string Dataset_DebugMode { get { return ResourceManager.GetString("Dataset_DebugMode", resourceCulture); } }
        public static string Dataset_DebugModeTooltip { get { return ResourceManager.GetString("Dataset_DebugModeTooltip", resourceCulture); } }
        public static string Dataset_DataAugmentation { get { return ResourceManager.GetString("Dataset_DataAugmentation", resourceCulture); } }
        public static string Dataset_Seed { get { return ResourceManager.GetString("Dataset_Seed", resourceCulture); } }
        public static string Dataset_SeedTooltip { get { return ResourceManager.GetString("Dataset_SeedTooltip", resourceCulture); } }
        public static string Dataset_ApplyToVal { get { return ResourceManager.GetString("Dataset_ApplyToVal", resourceCulture); } }
        public static string Dataset_ApplyToValTooltip { get { return ResourceManager.GetString("Dataset_ApplyToValTooltip", resourceCulture); } }
        public static string Dataset_ApplyToTest { get { return ResourceManager.GetString("Dataset_ApplyToTest", resourceCulture); } }
        public static string Dataset_ApplyToTestTooltip { get { return ResourceManager.GetString("Dataset_ApplyToTestTooltip", resourceCulture); } }
        public static string Dataset_TabGeometry { get { return ResourceManager.GetString("Dataset_TabGeometry", resourceCulture); } }
        public static string Dataset_TabColor { get { return ResourceManager.GetString("Dataset_TabColor", resourceCulture); } }
        public static string Dataset_TabNoiseBlur { get { return ResourceManager.GetString("Dataset_TabNoiseBlur", resourceCulture); } }
        public static string Dataset_TabAdvanced { get { return ResourceManager.GetString("Dataset_TabAdvanced", resourceCulture); } }
        public static string Dataset_TabPreview { get { return ResourceManager.GetString("Dataset_TabPreview", resourceCulture); } }
        public static string Dataset_TabPresets { get { return ResourceManager.GetString("Dataset_TabPresets", resourceCulture); } }
        public static string Dataset_AugmentationEnableTooltip { get { return ResourceManager.GetString("Dataset_AugmentationEnableTooltip", resourceCulture); } }
        public static string Dataset_RecommendationFormat { get { return ResourceManager.GetString("Dataset_RecommendationFormat", resourceCulture); } }
        public static string Dataset_Range { get { return ResourceManager.GetString("Dataset_Range", resourceCulture); } }
        public static string Dataset_RangeLowerTooltip { get { return ResourceManager.GetString("Dataset_RangeLowerTooltip", resourceCulture); } }
        public static string Dataset_DecrementLowerTooltip { get { return ResourceManager.GetString("Dataset_DecrementLowerTooltip", resourceCulture); } }
        public static string Dataset_IncrementLowerTooltip { get { return ResourceManager.GetString("Dataset_IncrementLowerTooltip", resourceCulture); } }
        public static string Dataset_RangeUpperTooltip { get { return ResourceManager.GetString("Dataset_RangeUpperTooltip", resourceCulture); } }
        public static string Dataset_DecrementUpperTooltip { get { return ResourceManager.GetString("Dataset_DecrementUpperTooltip", resourceCulture); } }
        public static string Dataset_IncrementUpperTooltip { get { return ResourceManager.GetString("Dataset_IncrementUpperTooltip", resourceCulture); } }
        public static string Dataset_Probability { get { return ResourceManager.GetString("Dataset_Probability", resourceCulture); } }
        public static string Dataset_ProbabilityTooltip { get { return ResourceManager.GetString("Dataset_ProbabilityTooltip", resourceCulture); } }
        public static string Dataset_DecrementProbTooltip { get { return ResourceManager.GetString("Dataset_DecrementProbTooltip", resourceCulture); } }
        public static string Dataset_IncrementProbTooltip { get { return ResourceManager.GetString("Dataset_IncrementProbTooltip", resourceCulture); } }
        public static string Dataset_MinProbTooltip { get { return ResourceManager.GetString("Dataset_MinProbTooltip", resourceCulture); } }
        public static string Dataset_MaxProbTooltip { get { return ResourceManager.GetString("Dataset_MaxProbTooltip", resourceCulture); } }
        public static string Dataset_ResetTooltip { get { return ResourceManager.GetString("Dataset_ResetTooltip", resourceCulture); } }
        public static string Dataset_TilesFolder { get { return ResourceManager.GetString("Dataset_TilesFolder", resourceCulture); } }
        public static string Dataset_TilesFolderTooltip { get { return ResourceManager.GetString("Dataset_TilesFolderTooltip", resourceCulture); } }
        public static string Dataset_BrowsePreviewTooltip { get { return ResourceManager.GetString("Dataset_BrowsePreviewTooltip", resourceCulture); } }
        public static string Dataset_ApplyNextTransform { get { return ResourceManager.GetString("Dataset_ApplyNextTransform", resourceCulture); } }
        public static string Dataset_ApplyNextTransformTooltip { get { return ResourceManager.GetString("Dataset_ApplyNextTransformTooltip", resourceCulture); } }
        public static string Dataset_ApplySelected { get { return ResourceManager.GetString("Dataset_ApplySelected", resourceCulture); } }
        public static string Dataset_ApplySelectedTooltip { get { return ResourceManager.GetString("Dataset_ApplySelectedTooltip", resourceCulture); } }
        public static string Dataset_ApplyingTransform { get { return ResourceManager.GetString("Dataset_ApplyingTransform", resourceCulture); } }
        public static string Dataset_CurrentTile { get { return ResourceManager.GetString("Dataset_CurrentTile", resourceCulture); } }
        public static string Dataset_CurrentTileTooltip { get { return ResourceManager.GetString("Dataset_CurrentTileTooltip", resourceCulture); } }
        public static string Dataset_PrevImageTooltip { get { return ResourceManager.GetString("Dataset_PrevImageTooltip", resourceCulture); } }
        public static string Dataset_NextImageTooltip { get { return ResourceManager.GetString("Dataset_NextImageTooltip", resourceCulture); } }
        public static string Dataset_PreviewInstructions { get { return ResourceManager.GetString("Dataset_PreviewInstructions", resourceCulture); } }
        public static string Dataset_Applied { get { return ResourceManager.GetString("Dataset_Applied", resourceCulture); } }
        public static string Dataset_BuiltInPresets { get { return ResourceManager.GetString("Dataset_BuiltInPresets", resourceCulture); } }
        public static string Dataset_PresetsDescription { get { return ResourceManager.GetString("Dataset_PresetsDescription", resourceCulture); } }
        public static string Dataset_PresetNoneTooltip { get { return ResourceManager.GetString("Dataset_PresetNoneTooltip", resourceCulture); } }
        public static string Dataset_PresetLightTooltip { get { return ResourceManager.GetString("Dataset_PresetLightTooltip", resourceCulture); } }
        public static string Dataset_PresetStandardTooltip { get { return ResourceManager.GetString("Dataset_PresetStandardTooltip", resourceCulture); } }
        public static string Dataset_PresetAggressiveTooltip { get { return ResourceManager.GetString("Dataset_PresetAggressiveTooltip", resourceCulture); } }
        public static string Dataset_PresetOutdoorAerialTooltip { get { return ResourceManager.GetString("Dataset_PresetOutdoorAerialTooltip", resourceCulture); } }
        public static string Dataset_SavePreset { get { return ResourceManager.GetString("Dataset_SavePreset", resourceCulture); } }
        public static string Dataset_SavePresetTooltip { get { return ResourceManager.GetString("Dataset_SavePresetTooltip", resourceCulture); } }
        public static string Dataset_LoadPreset { get { return ResourceManager.GetString("Dataset_LoadPreset", resourceCulture); } }
        public static string Dataset_LoadPresetTooltip { get { return ResourceManager.GetString("Dataset_LoadPresetTooltip", resourceCulture); } }
        public static string Dataset_ExportHyp { get { return ResourceManager.GetString("Dataset_ExportHyp", resourceCulture); } }
        public static string Dataset_ExportHypTooltip { get { return ResourceManager.GetString("Dataset_ExportHypTooltip", resourceCulture); } }
        public static string Dataset_Summary { get { return ResourceManager.GetString("Dataset_Summary", resourceCulture); } }
        public static string Dataset_EstimatedSourceImages { get { return ResourceManager.GetString("Dataset_EstimatedSourceImages", resourceCulture); } }
        public static string Dataset_DatasetMultiplierFormat { get { return ResourceManager.GetString("Dataset_DatasetMultiplierFormat", resourceCulture); } }
        public static string Dataset_EstimatedTotalFormat { get { return ResourceManager.GetString("Dataset_EstimatedTotalFormat", resourceCulture); } }
        public static string Dataset_EstimatedTimeFormat { get { return ResourceManager.GetString("Dataset_EstimatedTimeFormat", resourceCulture); } }
        public static string Dataset_RunTooltip { get { return ResourceManager.GetString("Dataset_RunTooltip", resourceCulture); } }
        public static string Dataset_CreateDataset { get { return ResourceManager.GetString("Dataset_CreateDataset", resourceCulture); } }
        public static string Dataset_Running { get { return ResourceManager.GetString("Dataset_Running", resourceCulture); } }
        public static string Dataset_TilesExistMessage { get { return ResourceManager.GetString("Dataset_TilesExistMessage", resourceCulture); } }
        public static string Dataset_TilesExistTitle { get { return ResourceManager.GetString("Dataset_TilesExistTitle", resourceCulture); } }
        public static string Dataset_OrthoNotFound { get { return ResourceManager.GetString("Dataset_OrthoNotFound", resourceCulture); } }

        public static string Daml_GroupCaption { get { return ResourceManager.GetString("Daml_GroupCaption", resourceCulture); } }
        public static string Daml_DetectionCaption { get { return ResourceManager.GetString("Daml_DetectionCaption", resourceCulture); } }
        public static string Daml_CreateDatasetCaption { get { return ResourceManager.GetString("Daml_CreateDatasetCaption", resourceCulture); } }
        public static string Daml_YoloDetectionCaption { get { return ResourceManager.GetString("Daml_YoloDetectionCaption", resourceCulture); } }
    }
}
